<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <IsPackable>false</IsPackable>
    <LangVersion>latest</LangVersion>
    <SimHubReferencePath Condition="'$(SimHubReferencePath)' == ''">$(MSBuildThisFileDirectory)..\lib\SimHub\</SimHubReferencePath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.4.3" />
    <PackageReference Include="MSTest.TestFramework" Version="3.4.3" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\\Affinity\\Affinity.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="PresentationCore" />
    <Reference Include="WindowsBase" />
    <Reference Include="SimHub.Plugins">
      <HintPath>$(SimHubReferencePath)SimHub.Plugins.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="SimHub.Logging">
      <HintPath>$(SimHubReferencePath)SimHub.Logging.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="GameReaderCommon">
      <HintPath>$(SimHubReferencePath)GameReaderCommon.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
